-- CCMath secondary build (library consumption). CMake is the primary build system.
-- Regenerate generated files:
--   cmake --build <build-dir> --target ccmath-generate-secondary-builds

-- BEGIN GENERATED LIBRARY MANIFEST
-- Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.
-- CMake is the primary build system.
--
-- Consumer usage:
--   include("path/to/ccmath/premake5.lua")
--   project "my-app"
--       kind "ConsoleApp"
--       language "C++"
--       files { "main.cpp" }
--       ccmath.use()

newoption {
    trigger = "ccmath-enable-runtime-simd",
    description = "Enable SIMD optimization for runtime evaluation (does not affect compile-time)",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "true",
}

newoption {
    trigger = "ccmath-disable-errno",
    description = "Disable the use of errno in ccmath during runtime (may lead to faster evaluations but is non-standard)",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "false",
}

newoption {
    trigger = "ccmath-disable-reduced-precision-powl",
    description = "Return quiet NaN from powl on non-binary80 long double instead of the default reduced-precision double fallback",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "false",
}

ccmath = ccmath or {}

local _ccmath_include_dirs = { "/Users/ianpike/Dev/ccmath/include", "/Users/ianpike/Dev/ccmath/out/secondary/include" }

local function _ccmath_option_enabled(trigger, default_value)
    local value = _OPTIONS[trigger]
    if value == nil then
        return default_value
    end
    return value == "true"
end

function ccmath.include_dirs()
    return _ccmath_include_dirs
end

function ccmath.defines()
    local defs = {}

    if _ccmath_option_enabled("ccmath-enable-runtime-simd", true) then
        table.insert(defs, "CCM_CONFIG_USE_RT_SIMD")
    end

    if _ccmath_option_enabled("ccmath-disable-errno", false) then
        table.insert(defs, "CCM_CONFIG_DISABLE_ERRNO")
    end

    if _ccmath_option_enabled("ccmath-disable-reduced-precision-powl", false) then
        table.insert(defs, "CCM_CONFIG_DISABLE_REDUCED_PRECISION_POWL")
    end

    return defs
end

function ccmath.use()
    includedirs(ccmath.include_dirs())
    defines(ccmath.defines())
end
-- END GENERATED LIBRARY MANIFEST
