-- CCMath secondary build (library consumption). CMake is the primary build system.
-- Regenerate generated files:
--   cmake --build <build-dir> --target ccmath-generate-secondary-builds

-- BEGIN GENERATED LIBRARY MANIFEST
-- Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.
-- CMake is the primary build system, but this module is self-contained.
--
-- Consumer usage:
--   include("path/to/ccmath/premake5.lua")
--   project "my-app"
--       kind "ConsoleApp"
--       language "C++"
--       files { "main.cpp" }
--       ccmath.use()

newoption {
    trigger = "ccmath-enable-runtime-simd",
    description = "Enable SIMD optimization for runtime evaluation (does not affect compile-time)",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "true",
}

newoption {
    trigger = "ccmath-disable-errno",
    description = "Disable the use of errno in ccmath during runtime (may lead to faster evaluations but is non-standard)",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "false",
}

newoption {
    trigger = "ccmath-disable-reduced-precision-powl",
    description = "Return quiet NaN from powl on non-binary80 long double instead of the default reduced-precision double fallback",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "false",
}

newoption {
    trigger = "ccmath-deterministic",
    description = "Produce bit-identical cross-hardware math: route transcendentals through the generic kernels (no libm), force the correctly-rounded FMA path, disable runtime SIMD, and evaluate long double in double precision (GCC/Clang)",
    allowed = { { "true", "Enable" }, { "false", "Disable" } },
    default = "false",
}

ccmath = ccmath or {}

-- Resolve paths against ccmath's own location, not the consumer's.
local _ccmath_root = _SCRIPT_DIR

-- Generate ccmath/version.hpp here so Premake consumers never depend on a CMake configure.
local _ccmath_version_header = [==[
/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#ifndef CCMATH_VERSION_HPP
#define CCMATH_VERSION_HPP

#define CCMATH_VERSION_MAJOR 0
#define CCMATH_VERSION_MINOR 3
#define CCMATH_VERSION_PATCH 0
// MAJOR.MINOR.PATCH packed into one integer, up to 3 digits (0 to 999) per component.
#define CCMATH_TO_VERSION(MAJOR, MINOR, PATCH) ((MAJOR) * 1000000 + (MINOR) * 1000 + (PATCH))
#define CCMATH_VERSION CCMATH_TO_VERSION(CCMATH_VERSION_MAJOR, CCMATH_VERSION_MINOR, CCMATH_VERSION_PATCH)

#endif // CCMATH_VERSION_HPP
]==]

local function _ccmath_write_version_header()
    local generated = path.join(_ccmath_root, "out/secondary/include/ccmath")
    os.mkdir(generated)
    local handle = io.open(path.join(generated, "version.hpp"), "w")
    handle:write(_ccmath_version_header)
    handle:close()
end

_ccmath_write_version_header()

local _ccmath_include_dirs = { "include", "out/secondary/include" }

local function _ccmath_option_enabled(trigger, default_value)
    local value = _OPTIONS[trigger]
    if value == nil then
        return default_value
    end
    return value == "true"
end

local function _ccmath_is_msvc()
    return string.match(_ACTION or "", "vs") ~= nil
end

function ccmath.include_dirs()
    local resolved = {}
    for _, dir in ipairs(_ccmath_include_dirs) do
        table.insert(resolved, path.getabsolute(path.join(_ccmath_root, dir)))
    end
    return resolved
end

function ccmath.defines()
    local defs = {}

    if _ccmath_option_enabled("ccmath-enable-runtime-simd", true) and not _ccmath_option_enabled("ccmath-deterministic", false) then
        table.insert(defs, "CCM_CONFIG_USE_RT_SIMD")
    end

    if _ccmath_option_enabled("ccmath-disable-errno", false) then
        table.insert(defs, "CCM_CONFIG_DISABLE_ERRNO")
    end

    if _ccmath_option_enabled("ccmath-disable-reduced-precision-powl", false) then
        table.insert(defs, "CCM_CONFIG_DISABLE_REDUCED_PRECISION_POWL")
    end

    if _ccmath_option_enabled("ccmath-deterministic", false) then
        table.insert(defs, "CCM_CONFIG_DETERMINISTIC")
    end

    return defs
end

function ccmath.buildoptions()
    local opts = {}

    if _ccmath_option_enabled("ccmath-deterministic", false) and not _ccmath_is_msvc() then
        table.insert(opts, "-ffp-contract=off")
    end

    return opts
end

function ccmath.use()
    includedirs(ccmath.include_dirs())
    defines(ccmath.defines())
    buildoptions(ccmath.buildoptions())
end
-- END GENERATED LIBRARY MANIFEST
