/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#pragma once

#include "ccmath/internal/math/generic/func/power/pow_impl/powf_data.hpp"
#include "ccmath/internal/math/generic/func/power/sqrt_gen.hpp"
#include "ccmath/internal/predef/has_builtin.hpp"
#include "ccmath/internal/support/bits.hpp"
#include "ccmath/internal/support/common_math_constants.hpp"
#include "ccmath/internal/support/fenv/fenv_support.hpp"
#include "ccmath/internal/support/fp/fp_bits.hpp"
#include "ccmath/internal/support/fp/nearest_integer.hpp"
#include "ccmath/internal/support/is_constant_evaluated.hpp"
#include "ccmath/internal/support/multiply_add.hpp"
#include "ccmath/internal/support/poly_eval.hpp"
#include "ccmath/internal/types/double_double.hpp"
#include "ccmath/math/compare/isnan.hpp"

#include <array>
#include <cstdint>
#include <limits>
#include <type_traits>

namespace ccm::gen::impl
{
	namespace internal::impl
	{
		namespace pow_kernel_detail
		{
			inline double fma_dx(double x, double y, double z) noexcept
			{
#if defined(CCMATH_TARGET_CPU_HAS_FMA)
				return support::multiply_add(x, y, z);
#elif CCM_HAS_BUILTIN(__builtin_fma)
				return __builtin_fma(x, y, z);
#else
				return (x * y) + z;
#endif
			}

			// Order operands for Fast2Sum (exact_add), which requires |a| >= |b|.
			constexpr bool larger_exponent(double a, double b) noexcept
			{
				using DoubleBits = support::fp::FPBits<double>;
				return DoubleBits(a).get_biased_exponent() >= DoubleBits(b).get_biased_exponent();
			}
		} // namespace pow_kernel_detail

		using ccm::types::DoubleDouble;

		constexpr bool is_odd_integer(double val) noexcept
		{
			using FPBits_t						 = support::fp::FPBits<double>;
			const std::uint64_t x_u				 = ccm::support::bit_cast<std::uint64_t>(val);
			const auto x_e						 = static_cast<std::int32_t>((x_u & FPBits_t::exponent_mask) >> FPBits_t::fraction_length);
			const std::int32_t lsb				 = support::countr_zero(x_u | FPBits_t::exponent_mask);
			constexpr std::int32_t unit_exponent = FPBits_t::exponent_bias + static_cast<std::int32_t>(FPBits_t::fraction_length);
			return (x_e + lsb == unit_exponent);
		}

		constexpr bool is_integer(double val) noexcept
		{
			using FPBits_t						 = support::fp::FPBits<double>;
			const std::uint64_t x_u				 = ccm::support::bit_cast<std::uint64_t>(val);
			const auto x_e						 = static_cast<std::int32_t>((x_u & FPBits_t::exponent_mask) >> FPBits_t::fraction_length);
			const std::int32_t lsb				 = support::countr_zero(x_u | FPBits_t::exponent_mask);
			constexpr std::int32_t unit_exponent = FPBits_t::exponent_bias + static_cast<std::int32_t>(FPBits_t::fraction_length);
			return (x_e + lsb >= unit_exponent);
		}

		// Generated by Sollya with:
		//   P = fpminimax(log2(1 + x)/x, 6, [|D...|], [-2^-8, 2^-7])
		inline constexpr std::array<double, 7> POW_LOG2_COEFFS = {
			0x1.71547652b82fep0,  -0x1.71547652b82e7p-1, 0x1.ec709dc3b1fd5p-2, -0x1.7154766124215p-2,
			0x1.2776bd90259d8p-2, -0x1.ec586c6f3d311p-3, 0x1.9c4775eccf524p-3,
		};

		// Generated by Sollya with:
		//   P = fpminimax(2^(x/64), 5, [|1, D...|], [-2^-1, 2^-1])
		inline constexpr std::array<double, 6> POW_EXP2_COEFFS = {
			0x1p0, 0x1.62e42fefa39efp-7, 0x1.ebfbdff82a23ap-15, 0x1.c6b08d7076268p-23, 0x1.3b2ad33f8b48bp-31, 0x1.5d870c4d84445p-40,
		};

		// Degree-5 double-double minimax for log2(1 + x)/x on the twice-reduced range.
		//   P = fpminimax(log2(1 + x)/x, 5, [|DD...|], [-0x1.3ffcp-15, 0x1.3e3dp-15])
		//   dirtyinfnorm(log2(1 + x)/x - P) = 0x1.8be5...p-96
		inline constexpr std::array<DoubleDouble, 6> POW_DD_LOG2P_COEFFS = {
			DoubleDouble{ 0x1.71547652b82fep0, 0x1.777d0ffda25ep-56 },	  DoubleDouble{ -0x1.71547652b82fep-1, -0x1.777d101cf0a84p-57 },
			DoubleDouble{ 0x1.ec709dc3a03fdp-2, 0x1.ce04b5140d867p-56 },  DoubleDouble{ -0x1.71547652b82fbp-2, 0x1.137b47e635be5p-56 },
			DoubleDouble{ 0x1.2776c516a92a2p-2, -0x1.b5a30b3bdb318p-58 }, DoubleDouble{ -0x1.ec70af1929ca6p-3, 0x1.2d2fbd081e657p-57 },
		};

		// Degree-9 double-double minimax for 2^(x/64), dirtyinfnorm ~ 2^-106.
		inline constexpr std::array<DoubleDouble, 10> POW_DD_EXP2_COEFFS = {
			DoubleDouble{ 0x1p0, 0 },
			DoubleDouble{ 0x1.62e42fefa39efp-7, 0x1.abc9e3b398024p-62 },
			DoubleDouble{ 0x1.ebfbdff82c58fp-15, -0x1.5e43a5429bddbp-69 },
			DoubleDouble{ 0x1.c6b08d704a0cp-23, -0x1.d33162491268fp-77 },
			DoubleDouble{ 0x1.3b2ab6fba4e77p-31, 0x1.4fb32d240a14ep-86 },
			DoubleDouble{ 0x1.5d87fe78a6731p-40, 0x1.e84e916be83ep-97 },
			DoubleDouble{ 0x1.430912f86bfb8p-49, -0x1.9a447bfddc5e6p-103 },
			DoubleDouble{ 0x1.ffcbfc588ded9p-59, -0x1.31a55719de47fp-113 },
			DoubleDouble{ 0x1.62c034beb8339p-68, -0x1.0ba57164eb36bp-122 },
			DoubleDouble{ 0x1.b5251ff97bee1p-78, -0x1.8483eabd9642dp-132 },
		};

		// Exact-as-possible integer powers via double-double exponentiation by squaring.
		// Used for small integer exponents, where the result can land within one ULP of a
		// power of two (or be exactly representable) and the log2/exp2 reconstruction cannot
		// resolve the last bit. The products use an FMA-based error-free transform, which is
		// exact under every rounding mode (Dekker's exact_mult is exact only to nearest).
		namespace pow_int_detail
		{
			using ccm::types::DoubleDouble;

			constexpr DoubleDouble two_prod(double a, double b) noexcept
			{
				const double hi = a * b;
				const double lo = ccm::types::exact_fma(a, b, -hi);
				return DoubleDouble{ hi, lo };
			}

			constexpr DoubleDouble mul(const DoubleDouble & a, const DoubleDouble & b) noexcept
			{
				DoubleDouble p	= two_prod(a.hi, b.hi);
				const double t1 = ccm::types::exact_fma(a.hi, b.lo, p.lo);
				const double t2 = ccm::types::exact_fma(a.lo, b.hi, t1);
				return ccm::types::exact_add(p.hi, t2);
			}

			constexpr DoubleDouble ipow(DoubleDouble factor, std::uint64_t e) noexcept
			{
				DoubleDouble result{ 1.0, 0.0 };
				while (e > 0U)
				{
					if ((e & 1U) != 0U) { result = mul(result, factor); }
					e >>= 1U;
					if (e > 0U) { factor = mul(factor, factor); }
				}
				return result;
			}

			constexpr DoubleDouble ipow(double base, std::uint64_t e) noexcept
			{ return ipow(DoubleDouble{ base, 0.0 }, e); }

			// sqrt(x) refined to a double-double via one Newton correction on a correctly
			// rounded seed: x^(k + 1/2) = sqrt(x)^(2k + 1) is then exact integer exponentiation.
			// Tiny x is scaled up first so that s0^2 stays in the normal range, otherwise the
			// two_prod residual underflows and the correction is lost.
			constexpr DoubleDouble dd_sqrt(double x) noexcept
			{
				double mult = 1.0;
				if (x < 0x1.0p-1000)
				{
					x *= 0x1.0p106;
					mult = 0x1.0p-53;
				}
				const double s0		  = ccm::gen::sqrt_gen<double>(x);
				const DoubleDouble sq = two_prod(s0, s0);
				const double e		  = (x - sq.hi) - sq.lo; // x - s0^2 (exact)
				const double corr	  = e / (2.0 * s0);
				return ccm::types::exact_add(s0 * mult, corr * mult);
			}

			// 1 / (p.hi + p.lo), refined to one rounding by a Newton step on the pair.
			constexpr double reciprocal(const DoubleDouble & p) noexcept
			{
				using FPBits_t			   = support::fp::FPBits<double>;
				const DoubleDouble divisor = ccm::types::exact_add(p.hi, p.lo);
				const double r0			   = 1.0 / divisor.hi;
				const FPBits_t r0_bits(r0);
				if (r0 == 0.0 || !r0_bits.is_finite()) { return r0; }
				// An exact single-double divisor (e.g. x^-1) is reciprocated correctly by IEEE
				// division in every rounding mode. The Newton refinement below targets a genuine
				// double-double divisor and would re-round r0 to the wrong neighbor here.
				if (divisor.lo == 0.0) { return r0; }

				// Keep both Newton steps fused so software-FMA backends such as MSVC preserve the
				// full double-double correction instead of bleeding precision through intermediate
				// rounding in the residual and update terms.
				auto refine = [&divisor](double r) constexpr noexcept
				{
					const DoubleDouble pr = two_prod(divisor.hi, r);
					const double err_hi	  = (1.0 - pr.hi) - pr.lo;
					const double err	  = ccm::types::exact_fma(-divisor.lo, r, err_hi);
					return ccm::types::exact_fma(r, err, r);
				};

				return refine(refine(r0));
			}
		} // namespace pow_int_detail

		// Accurate double-double reconstruction of x^y for the in-range (non-clamped)
		// exponent region. The fast pow_kernel single-double path is good to a few ULP
		// but loses the last bit near rounding boundaries under directed rounding. This
		// path mirrors powf_double_double but keeps a full double-double log2(x) (binary64
		// allows |y| up to ~2^53, so the powf lo6_hi single-double shortcut is unsafe). A
		// normal final value collapses with a single binary64 addition, correctly rounded in
		// every mode; a subnormal value (only reachable through the 2^-512 underflow scale) is
		// instead rounded straight onto the subnormal grid to avoid a double rounding.
		constexpr double pow_double_double(unsigned idx_x, double dx, double e_x, double y6, std::uint64_t sign, double scale) noexcept
		{
			using FPBits_t = support::fp::FPBits<double>;

			// Second range reduction:
			//   idx2 = round(dx * 2^14 + 2^6), dx2 = (1 + dx) * R2[idx2] - 1,
			//   with -0x1.3ffcp-15 <= dx2 <= 0x1.3e3dp-15.
			// The powf path can keep dx2 in a single double because its dx derives from a
			// 24-bit float, so (1 + dx) * R2 is exact. Here dx is full binary64 precision,
			// so (1 + dx) * R2 - 1 must be carried as a double-double or the reduction loses
			// roughly 2^-52, which feeds straight through into the result.
			const int idx2				   = static_cast<int>(support::fp::nearest_integer(support::multiply_add(dx, 0x1.0p14, 0x1.0p6)));
			const double r2				   = support::constants::R2.at(static_cast<std::size_t>(idx2));
			const DoubleDouble one_plus_dx = ccm::types::exact_add(1.0, dx);
			const DoubleDouble r2_prod	   = quick_mult(r2, one_plus_dx);
			const double dx2_hi			   = r2_prod.hi - 1.0; // Exact by Sterbenz, r2_prod.hi ~ 1
			const DoubleDouble dx2		   = ccm::types::exact_add(dx2_hi, r2_prod.lo);

			const DoubleDouble p = ::ccm::support::polyeval(dx2,
															POW_DD_LOG2P_COEFFS[0],
															POW_DD_LOG2P_COEFFS[1],
															POW_DD_LOG2P_COEFFS[2],
															POW_DD_LOG2P_COEFFS[3],
															POW_DD_LOG2P_COEFFS[4],
															POW_DD_LOG2P_COEFFS[5]);

			// log2(1 + dx2) ~ dx2 * P(dx2)
			const DoubleDouble log2_1p = quick_mult(dx2, p);

			// Lower-order parts of (e_x - log2(r1)) and -log2(r2). LOG2_R2_DD is stored {lo, hi}.
			const auto & lr = LOG2_R_TD.at(static_cast<std::size_t>(idx_x));
			const DoubleDouble log2_x_mid{ lr.mid, lr.lo };
			const auto & lr2 = LOG2_R2_DD.at(static_cast<std::size_t>(idx2));
			const DoubleDouble log2_r2_dd{ lr2.lo, lr2.hi };
			const DoubleDouble log2_x_m = ccm::types::add(log2_r2_dd, log2_x_mid);

			const DoubleDouble log2_x_low =
				pow_kernel_detail::larger_exponent(log2_x_m.hi, log2_1p.hi) ? ccm::types::add(log2_x_m, log2_1p) : ccm::types::add(log2_1p, log2_x_m);

			// Full log2(x) = (e_x - log2(r1) high part) + lower-order double-double. e_x + lr.hi
			// must be formed as an exact_add: for a base far from 1 the integer e_x is large and
			// rounds off the low bits of lr.hi, a residual of up to half an ulp of e_x that y6
			// then amplifies into more than a full result ulp. The single-double fast path keeps
			// this residual via its own exact_add, so the accurate path has to as well.
			const DoubleDouble hi_dd	= ccm::types::exact_add(e_x, lr.hi);
			const double log2_x_hi_part = hi_dd.hi;
			const DoubleDouble log2_x =
				pow_kernel_detail::larger_exponent(log2_x_hi_part, log2_x_low.hi) ? ccm::types::add(hi_dd, log2_x_low) : ccm::types::add(log2_x_low, hi_dd);

			// 2^6 * y * log2(x). In the gated range |y6_log2_x.hi| < 512 * 2^6.
			DoubleDouble y6_log2_x = quick_mult(y6, log2_x);

			// For over/underflow-adjacent results the caller passes scale = 2^+-512 and we shift
			// the binary exponent so the power-of-two reconstruction below stays representable.
			// The result is reassembled by multiplying the (normal) reconstruction by scale,
			// which is exact for a normal final value, so it stays correctly rounded.
			if (scale != 1.0) { y6_log2_x.hi += (scale > 1.0) ? -512.0 * 0x1.0p6 : 512.0 * 0x1.0p6; }

			const double hm		   = support::fp::nearest_integer(y6_log2_x.hi);
			const double lo6_hi	   = y6_log2_x.hi - hm; // Exact, |lo6_hi| <= 0.5
			const DoubleDouble lo6 = ccm::types::exact_add(lo6_hi, y6_log2_x.lo);

			const int hm_i		 = static_cast<int>(hm);
			const unsigned idx_y = static_cast<unsigned>(hm_i) & 0x3f;

			const std::int64_t exp2_hi_i =
				static_cast<std::int64_t>(static_cast<std::uint64_t>(static_cast<std::int64_t>(hm_i >> 6)) << FPBits_t::fraction_length);
			const std::int64_t exp2_mid_hi_i =
				static_cast<std::int64_t>(FPBits_t(support::constants::EXP2_MID1.at(static_cast<std::size_t>(idx_y)).hi).uintval());
			const std::int64_t exp2_mid_lo_i =
				static_cast<std::int64_t>(FPBits_t(support::constants::EXP2_MID1.at(static_cast<std::size_t>(idx_y)).mid).uintval());

			const std::uint64_t exp2_hm_hi_i = static_cast<std::uint64_t>(exp2_hi_i + exp2_mid_hi_i) + sign;
			const std::uint64_t exp2_hm_lo_i = idx_y != 0 ? static_cast<std::uint64_t>(exp2_hi_i + exp2_mid_lo_i) + sign : sign;

			const DoubleDouble exp2_hm{ FPBits_t(exp2_hm_hi_i).get_val(), FPBits_t(exp2_hm_lo_i).get_val() };

			const DoubleDouble pp = ::ccm::support::polyeval(lo6,
															 POW_DD_EXP2_COEFFS[0],
															 POW_DD_EXP2_COEFFS[1],
															 POW_DD_EXP2_COEFFS[2],
															 POW_DD_EXP2_COEFFS[3],
															 POW_DD_EXP2_COEFFS[4],
															 POW_DD_EXP2_COEFFS[5],
															 POW_DD_EXP2_COEFFS[6],
															 POW_DD_EXP2_COEFFS[7],
															 POW_DD_EXP2_COEFFS[8],
															 POW_DD_EXP2_COEFFS[9]);
			const DoubleDouble rr = quick_mult(exp2_hm, pp);

			// A single binary64 addition of a faithful double-double rounds once in the
			// active mode, yielding the correctly-rounded result for a normal final value. When
			// scale != 1 the reconstruction is built at normal magnitude and shifted by a
			// power-of-two scale; that shift is exact while the result stays normal, so the lone
			// addition is still correctly rounded there.
			const double collapsed = rr.hi + rr.lo;
			double result		   = collapsed * scale;

			// Once the scaled result lands in the subnormal range the 2^-512 shift rounds a second
			// time, so the collapse above double-rounds (off by one ULP under FE_TONEAREST). A
			// round-to-odd intermediate cannot rescue it: a 53-bit double leaves only one guard
			// bit over a 52-bit subnormal, while round-to-odd needs two. Instead round the
			// double-double straight onto the subnormal grid in one active-mode rounding; the
			// following power-of-two shift is then exact. Normal results keep the fast path
			// untouched (a normal reconstruction times a power-of-two scale is already exact).
			if (scale < 1.0)
			{
				if (const FPBits_t rb(result); rb.is_subnormal() || rb.is_zero())
				{
					// Every subnormal shares the lsb 2^-1074; with scale = 2^-512 the pre-scale grid
					// is 2^-562, so scaling the pair up by 2^562 makes that grid the unit and the
					// magnitude at most 2^51 (exact, no overflow). Round the integer count of grid
					// units in the active mode, then reattach the 2^-1074 weight exactly.
					constexpr double kGridToUnit   = 0x1.0p562;
					constexpr double kUnitToResult = 0x1.0p-1074;

					const bool neg		 = rr.hi < 0.0;
					const double abs_hi	 = neg ? -rr.hi : rr.hi;
					const double abs_lo	 = neg ? -rr.lo : rr.lo;
					const DoubleDouble v = ccm::types::exact_add(abs_hi * kGridToUnit, abs_lo * kGridToUnit);

					auto units	= static_cast<std::int64_t>(v.hi); // trunc toward zero, v.hi >= 0
					double frac = (v.hi - static_cast<double>(units)) + v.lo;
					if (frac < 0.0)
					{
						units -= 1;
						frac += 1.0;
					}

					const bool inexact = frac != 0.0;
					bool round_up_mag  = false;
					switch (support::fenv::get_rounding_mode())
					{
					case FE_TONEAREST: round_up_mag = frac > 0.5 || (frac == 0.5 && (units & 1) != 0); break;
					case FE_UPWARD: round_up_mag = !neg && inexact; break;
					case FE_DOWNWARD: round_up_mag = neg && inexact; break;
					case FE_TOWARDZERO:
					default: break;
					}
					if (round_up_mag) { units += 1; }

					const double magnitude = static_cast<double>(units) * kUnitToResult; // exact, units <= 2^52
					result				   = neg ? -magnitude : magnitude;
				}
			}

			return result;
		}

		constexpr double pow_kernel(double base, double exp, std::uint64_t sign) noexcept
		{
			using FPBits_t = support::fp::FPBits<double>;

			FPBits_t base_bits(base);
			int exponent_adjust = 0;

			if (base_bits.is_subnormal())
			{
				base *= 0x1.0p52;
				base_bits		= FPBits_t(base);
				exponent_adjust = -52;
			}

			const int e_x				   = static_cast<int>(base_bits.get_biased_exponent()) - FPBits_t::exponent_bias + exponent_adjust;
			const std::uint64_t x_mantissa = base_bits.uintval() & FPBits_t::fraction_mask;
			const unsigned idx_x		   = static_cast<unsigned>(x_mantissa >> (FPBits_t::fraction_length - 7));
			const double m_x			   = FPBits_t(x_mantissa | FPBits_t(1.0).uintval()).get_val();

			double dx = 0.0;
			DoubleDouble dx_c0{ 0.0, 0.0 };

			if (support::is_constant_evaluated())
			{
				const typename FPBits_t::storage_type masked_mantissa = static_cast<typename FPBits_t::storage_type>(
					FPBits_t(m_x).uintval() & static_cast<typename FPBits_t::storage_type>(0x3fff'e000'0000'0000ULL));
				const double c = FPBits_t(masked_mantissa).get_val();
				dx			   = support::multiply_add(
					support::constants::RD.at(static_cast<std::size_t>(idx_x)), m_x - c, support::constants::CD.at(static_cast<std::size_t>(idx_x)));
				dx_c0 = ccm::types::exact_mult(POW_LOG2_COEFFS[0], dx);
			}
			else
			{
				if constexpr (ccm::builtin::target_cpu_has_fma)
				{
					dx	  = pow_kernel_detail::fma_dx(support::constants::RD.at(static_cast<std::size_t>(idx_x)), m_x, -1.0);
					dx_c0 = ccm::types::exact_mult(POW_LOG2_COEFFS[0], dx);
				}
				else
				{
					const typename FPBits_t::storage_type masked_mantissa = static_cast<typename FPBits_t::storage_type>(
						FPBits_t(m_x).uintval() & static_cast<typename FPBits_t::storage_type>(0x3fff'e000'0000'0000ULL));
					const double c = FPBits_t(masked_mantissa).get_val();
					dx			   = support::multiply_add(
						support::constants::RD.at(static_cast<std::size_t>(idx_x)), m_x - c, support::constants::CD.at(static_cast<std::size_t>(idx_x)));
					dx_c0 = ccm::types::exact_mult(POW_LOG2_COEFFS[0], dx);
				}
			}

			const double dx2 = dx * dx;
			const double c0	 = support::multiply_add(dx, POW_LOG2_COEFFS[2], POW_LOG2_COEFFS[1]);
			const double c1	 = support::multiply_add(dx, POW_LOG2_COEFFS[4], POW_LOG2_COEFFS[3]);
			const double c2	 = support::multiply_add(dx, POW_LOG2_COEFFS[6], POW_LOG2_COEFFS[5]);
			const double p	 = support::polyeval(dx2, c0, c1, c2);

			const auto & log2_r			= LOG2_R_TD.at(static_cast<std::size_t>(idx_x));
			const double log2_x_hi_part = static_cast<double>(e_x) + log2_r.hi;
			DoubleDouble log2_x_hi		= ccm::types::exact_add(log2_x_hi_part, dx_c0.hi);
			const double log2_x_lo		= support::multiply_add(dx2, p, dx_c0.lo + log2_r.mid);

			DoubleDouble log2_x = ccm::types::exact_add(log2_x_hi.hi, log2_x_lo);
			log2_x.lo += log2_x_hi.lo + log2_r.lo;

			const double y6 = exp * 0x1.0p6;

			DoubleDouble y6_log2_x = ccm::types::exact_mult(y6, log2_x.hi);
			y6_log2_x.lo		   = support::multiply_add(y6, log2_x.lo, y6_log2_x.lo);

			double scale					 = 1.0;
			bool clamped					 = false;
			constexpr double upper_exp_bound = 512.0 * 0x1.0p6;

			if (FPBits_t(y6_log2_x.hi).abs().get_val() >= upper_exp_bound)
			{
				if (FPBits_t(y6_log2_x.hi).sign().is_pos())
				{
					scale = 0x1.0p512;
					y6_log2_x.hi -= 512.0 * 64.0;
					if (y6_log2_x.hi > 513.0 * 64.0)
					{
						y6_log2_x.hi = 513.0 * 64.0;
						// If hi is clamped, the huge double-double tail would dominate lo6 and
						// reconstruct a spurious value instead of cleanly overflowing to infinity.
						y6_log2_x.lo = 0.0;
						clamped		 = true;
					}
				}
				else
				{
					scale = 0x1.0p-512;
					y6_log2_x.hi += 512.0 * 64.0;
					if (y6_log2_x.hi < (-1076.0 + 512.0) * 64.0)
					{
						y6_log2_x.hi = -564.0 * 64.0;
						// If hi is clamped, a huge double-double tail would dominate lo6 and
						// reconstruct a spurious normal instead of flushing to zero.
						y6_log2_x.lo = 0.0;
						clamped		 = true;
					}
				}
			}

			// Every finite result, including the over/underflow-adjacent band that needs a
			// 2^+-512 scale, is reconstructed by the accurate double-double path so it stays
			// correctly rounded in every mode (the single-double fast path below loses several
			// ULP once the exponent leaves the unscaled range). Only genuine overflow/underflow
			// whose exponent is clamped keeps the fast path, where the value saturates to inf/0
			// and only the raised flag matters.
			if (!clamped)
			{
				const double dd = pow_double_double(idx_x, dx, static_cast<double>(e_x), y6, sign, scale);
				if (scale != 1.0)
				{
					const FPBits_t dd_bits(dd);
					if (dd_bits.is_inf())
					{
						support::fenv::set_errno_if_required(ERANGE);
						support::fenv::raise_except_if_required(FE_OVERFLOW);
					}
					else if (dd_bits.is_zero() || dd_bits.abs().uintval() < FPBits_t::min_normal().uintval())
					{
						support::fenv::set_errno_if_required(ERANGE);
						support::fenv::raise_except_if_required(FE_UNDERFLOW);
					}
				}
				return dd;
			}

			const double hm		= support::fp::nearest_integer(y6_log2_x.hi);
			const double lo6_hi = y6_log2_x.hi - hm;
			const double lo6	= lo6_hi + y6_log2_x.lo;

			const int hm_i		 = static_cast<int>(hm);
			const unsigned idx_y = static_cast<unsigned>(hm_i) & 0x3f;

			const std::int64_t exp2_hi_i =
				static_cast<std::int64_t>(static_cast<std::uint64_t>(static_cast<std::int64_t>(hm_i >> 6)) << FPBits_t::fraction_length);
			const std::int64_t exp2_mid_hi_i =
				static_cast<std::int64_t>(FPBits_t(support::constants::EXP2_MID1.at(static_cast<std::size_t>(idx_y)).hi).uintval());
			const std::int64_t exp2_mid_lo_i =
				static_cast<std::int64_t>(FPBits_t(support::constants::EXP2_MID1.at(static_cast<std::size_t>(idx_y)).mid).uintval());

			const std::uint64_t exp2_hm_hi_i = static_cast<std::uint64_t>(exp2_hi_i + exp2_mid_hi_i) + sign;
			const std::uint64_t exp2_hm_lo_i = idx_y != 0 ? static_cast<std::uint64_t>(exp2_hi_i + exp2_mid_lo_i) + sign : sign;

			const double exp2_hm_hi = FPBits_t(exp2_hm_hi_i).get_val();
			const double exp2_hm_lo = FPBits_t(exp2_hm_lo_i).get_val();

			const double lo6_sqr = lo6 * lo6;
			const double d0		 = support::multiply_add(lo6, POW_EXP2_COEFFS[2], POW_EXP2_COEFFS[1]);
			const double d1		 = support::multiply_add(lo6, POW_EXP2_COEFFS[4], POW_EXP2_COEFFS[3]);
			const double pp		 = support::polyeval(lo6_sqr, d0, d1, POW_EXP2_COEFFS[5]);

			double result = support::multiply_add(exp2_hm_hi * lo6, pp, exp2_hm_lo);
			result += exp2_hm_hi;

			double final = result * scale;
			if (sign == 0)
			{
				FPBits_t final_bits(final);
				if (final_bits.sign().is_neg())
				{
					if (final_bits.is_inf())
					{
						support::fenv::set_errno_if_required(ERANGE);
						support::fenv::raise_except_if_required(FE_OVERFLOW);
						final = FPBits_t::inf(types::Sign::POS).get_val();
					}
					else
					{
						support::fenv::set_errno_if_required(ERANGE);
						support::fenv::raise_except_if_required(FE_UNDERFLOW);
						final = 0.0;
					}
				}
				else if (scale == 0x1.0p-512 && final_bits.is_finite() && !final_bits.is_zero() &&
						 final_bits.abs().uintval() < FPBits_t::min_subnormal().uintval())
				{
					support::fenv::set_errno_if_required(ERANGE);
					support::fenv::raise_except_if_required(FE_UNDERFLOW);
					final = 0.0;
				}
			}

			return final;
		}

		constexpr double pow_impl(double base, double exp) noexcept
		{
			using FPBits_t = support::fp::FPBits<double>;
			using Sign	   = types::Sign;

			FPBits_t base_bits(base);
			FPBits_t exp_bits(exp);

			// Screen the operands by bit inspection so no floating point compare touches a
			// signaling NaN. UCRT's pow returns quietly for sNaN operands while glibc and
			// Apple libm signal invalid, so the raise is explicit and platform scoped.
#if !defined(_WIN32)
			if (base_bits.is_signaling_nan() || exp_bits.is_signaling_nan()) { support::fenv::raise_except_if_required(FE_INVALID); }
#endif

			if (exp_bits.is_zero()) { return 1.0; }								// pow(x, +/-0) = 1, including NaN x
			if (base_bits.uintval() == FPBits_t(1.0).uintval()) { return 1.0; } // pow(1, y) = 1, including NaN y

			if (base_bits.is_nan() || exp_bits.is_nan()) { return std::numeric_limits<double>::quiet_NaN(); }

			if (base_bits.is_zero())
			{
				const bool out_is_neg = base_bits.sign().is_neg() && is_odd_integer(exp);

				if (exp < 0.0)
				{
					support::fenv::set_errno_if_required(EDOM);
					support::fenv::raise_except_if_required(FE_DIVBYZERO);
					return FPBits_t::inf(out_is_neg ? Sign::NEG : Sign::POS).get_val();
				}

				return out_is_neg ? -0.0 : 0.0;
			}

			if (base_bits.is_inf())
			{
				// pow(+/-inf, y) is never a domain error. A negative infinite base only flips the
				// result sign when the exponent is an odd integer, otherwise the magnitude rule for
				// +inf applies (including non-integer exponents, e.g. pow(-inf, 0.5) = +inf).
				const bool out_is_neg = base_bits.sign().is_neg() && is_odd_integer(exp);
				if (exp < 0.0) { return out_is_neg ? -0.0 : 0.0; }
				return FPBits_t::inf(out_is_neg ? Sign::NEG : Sign::POS).get_val();
			}

			if (exp_bits.is_inf())
			{
				const std::uint64_t base_abs = base_bits.abs().uintval();
				const std::uint64_t one_bits = FPBits_t(1.0).uintval();

				if (base_abs == one_bits) { return 1.0; }

				if (exp_bits.sign().is_neg()) { return base_abs < one_bits ? std::numeric_limits<double>::infinity() : 0.0; }

				return base_abs < one_bits ? 0.0 : std::numeric_limits<double>::infinity();
			}

			if (base < 0.0 && !is_integer(exp))
			{
				support::fenv::set_errno_if_required(EDOM);
				support::fenv::raise_except_if_required(FE_INVALID);
				return std::numeric_limits<double>::quiet_NaN();
			}

			std::uint64_t sign = 0;
			if (base < 0.0)
			{
				if (is_odd_integer(exp)) { sign = FPBits_t::sign_mask; }
				base = base_bits.abs().get_val();
			}

			// The accurate integer path requires its positive power |base|^|exp| (held as p) to
			// stay in a comfortably normal band: once p.hi nears the subnormal floor the
			// double-double lo limb underflows during squaring and the running product loses the
			// extra precision the path exists to provide (this bites a tiny base with a large
			// negative exponent, whose reciprocal is a large normal result). Powers outside the
			// band, and non-normal results, fall through to the kernel, which owns errno and the
			// floating-point exception signaling.
			constexpr double kIntPowSafeHi = 0x1.0p960;
			constexpr double kIntPowSafeLo = 0x1.0p-960;

			// Small integer exponents: double-double exponentiation by squaring rounds correctly
			// even for results sitting within one ULP of a power of two, which the log2/exp2 kernel
			// cannot.
			if (is_integer(exp) && FPBits_t(exp).abs().get_val() <= 1024.0)
			{
				const auto exp_i			   = static_cast<std::int64_t>(exp);
				const std::uint64_t mag		   = exp_i < 0 ? static_cast<std::uint64_t>(-(exp_i + 1)) + 1U : static_cast<std::uint64_t>(exp_i);
				pow_int_detail::DoubleDouble p = pow_int_detail::ipow(base, mag);
				if (const double p_abs = FPBits_t(p.hi).abs().get_val(); p_abs >= kIntPowSafeLo && p_abs <= kIntPowSafeHi)
				{
					// Fold a negative result's sign into the pair before the final rounding. Negating
					// a magnitude that was already rounded in the active mode flips directed rounding
					// (-round_up(|v|) is round_down(-|v|)); rounding the signed value is correct.
					if (sign != 0)
					{
						p.hi = -p.hi;
						p.lo = -p.lo;
					}
					const double r = exp_i < 0 ? pow_int_detail::reciprocal(p) : (p.hi + p.lo);
					if (const FPBits_t r_bits(r); r_bits.is_finite() && !r_bits.is_zero() && !r_bits.is_subnormal()) { return r; }
				}
			}

			// Small half-integer exponents: x^(k + 1/2) = sqrt(x)^(2k + 1). Here base > 0
			// (negative base with non-integer exponent already returned NaN), so the result is
			// a correctly rounded integer power of an accurate double-double sqrt.
			const double two_exp = exp * 2.0;
			if (is_integer(two_exp) && FPBits_t(two_exp).abs().get_val() <= 2048.0)
			{
				// pow(x, 1/2) is exactly the correctly rounded sqrt. The double-double round
				// trip below would re-round an exact midpoint to the wrong neighbor.
				if (exp == 0.5) { return ccm::gen::sqrt_gen<double>(base); }

				const auto m						 = static_cast<std::int64_t>(two_exp);
				const std::uint64_t mag				 = m < 0 ? static_cast<std::uint64_t>(-(m + 1)) + 1U : static_cast<std::uint64_t>(m);
				const pow_int_detail::DoubleDouble p = pow_int_detail::ipow(pow_int_detail::dd_sqrt(base), mag);
				if (const double p_abs = FPBits_t(p.hi).abs().get_val(); p_abs >= kIntPowSafeLo && p_abs <= kIntPowSafeHi)
				{
					const double r = m < 0 ? pow_int_detail::reciprocal(p) : (p.hi + p.lo);
					if (const FPBits_t r_bits(r); r_bits.is_finite() && !r_bits.is_zero() && !r_bits.is_subnormal()) { return r; }
				}
			}

			// LLVM libc clamps huge finite exponents so the kernel can round overflow/underflow.
			const FPBits_t exp_abs_bits(exp);
			const std::uint64_t exp_a					   = exp_abs_bits.abs().uintval();
			constexpr std::uint64_t kHugeExponentThreshold = 0x43d7'4910'd52d'3052ULL;
			if (exp_a > kHugeExponentThreshold) { exp = exp_abs_bits.sign().is_neg() ? -0x1.0p100 : 0x1.0p100; }

			return pow_kernel(base, exp, sign);
		}
	} // namespace internal::impl

	constexpr double pow_impl(double base, double exp) noexcept
	{ return internal::impl::pow_impl(base, exp); }

} // namespace ccm::gen::impl
