/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

// Lookup tables and constants for float sin/cos.
// Adapted from LLVM-libc (libc/src/__support/math/sincosf_float_eval.h).

#pragma once

#include "ccmath/internal/types/double_double.hpp"

#include <array>
#include <cstddef>

namespace ccm::internal::sincos_float_data
{
	using DoubleDouble = ccm::types::DoubleDouble;

	// sin(k * pi/8) for k = 0..15, generated by Sollya.
	constexpr std::array<float, 16> SIN_K_PI_OVER_8 = {
		0.0f,		 0x1.87de2ap-2f, 0x1.6a09e6p-1f, 0x1.d906bcp-1f, 1.0f,		 0x1.d906bcp-1f, 0x1.6a09e6p-1f, 0x1.87de2ap-2f,
		0.0f,		 -0x1.87de2ap-2f, -0x1.6a09e6p-1f, -0x1.d906bcp-1f, -1.0f, -0x1.d906bcp-1f, -0x1.6a09e6p-1f, -0x1.87de2ap-2f,
	};

	// Multi-part pi/8 for small range reduction.
	constexpr std::array<float, 3> MPI = { -0x1.921f8p-2f, -0x1.aa22p-21f, -0x1.68c234p-41f };

	constexpr float ONE_OVER_PI = 0x1.45f306p+1f;

	// Scaled 8/pi digits for large range reduction.
	constexpr std::array<std::array<float, 4>, 14> EIGHT_OVER_PI = { {
		{ 0x1.000146p1f, -0x1.9f246cp-28f, -0x1.bbead6p-54f, -0x1.ec5418p-85f },
		{ 0x1.0145f4p1f, -0x1.f246c6p-24f, (-0x1.df56bp-49f), -0x1.ec5418p-77f },
		{ 0x1.45f306p1f, 0x1.b9391p-24f, 0x1.529fc2p-50f, 0x1.d5f47ep-76f },
		{ 0x1.f306dcp1f, 0x1.391054p-24f, 0x1.4fe13ap-49f, 0x1.7d1f54p-74f },
		{ -0x1.f246c6p0f, (-0x1.df56bp-25f), -0x1.ec5418p-53f, 0x1.f534dep-78f },
		{ -0x1.236378p1f, 0x1.529fc2p-26f, 0x1.d5f47ep-52f, -0x1.65912p-77f },
		{ 0x1.391054p0f, 0x1.4fe13ap-25f, 0x1.7d1f54p-50f, -0x1.6447e4p-75f },
		{ 0x1.1054a8p0f, -0x1.ec5418p-29f, 0x1.f534dep-54f, -0x1.f924ecp-81f },
		{ 0x1.529fc2p-2f, 0x1.d5f47ep-28f, -0x1.65912p-53f, 0x1.b6c52cp-79f },
		{ -0x1.ac07b2p1f, 0x1.5f47d4p-24f, 0x1.a6ee06p-49f, 0x1.b6295ap-74f },
		{ -0x1.ec5418p-5f, 0x1.f534dep-30f, -0x1.f924ecp-57f, 0x1.5993c4p-82f },
		{ 0x1.3abe9p-1f, -0x1.596448p-27f, 0x1.b6c52cp-55f, -0x1.9b0ef2p-80f },
		{ -0x1.505c16p1f, 0x1.a6ee06p-25f, 0x1.b6295ap-50f, -0x1.b0ef1cp-76f },
		{ -0x1.70565ap-1f, 0x1.dc0db6p-26f, 0x1.4acc9ep-53f, 0x1.0e4108p-80f },
	} };

	constexpr DoubleDouble PI_OVER_8 = { -0x1.777a5cp-27f, 0x1.921fb6p-2f };

} // namespace ccm::internal::sincos_float_data
