/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#pragma once

#include <array>

namespace ccm::internal::sincos_double_data
{

	// All small-range constants are genuine binary64 (the float kernel's constants promoted to
	// double would carry only ~24 bits and make the double kernel float-grade). Generated by
	// Sollya at 250-bit precision.

	// sin(k * pi/8) for k = 0..15, correctly rounded to double.
	constexpr std::array<double, 16> SIN_K_PI_OVER_8 = {
		0.0, 0x1.87de2a6aea963p-2,	0x1.6a09e667f3bcdp-1,  0x1.d906bcf328d46p-1,  1.0,	0x1.d906bcf328d46p-1,  0x1.6a09e667f3bcdp-1,  0x1.87de2a6aea963p-2,
		0.0, -0x1.87de2a6aea963p-2, -0x1.6a09e667f3bcdp-1, -0x1.d906bcf328d46p-1, -1.0, -0x1.d906bcf328d46p-1, -0x1.6a09e667f3bcdp-1, -0x1.87de2a6aea963p-2,
	};

	// Cody-Waite three-part -pi/8 for the small-range reduction. The high part has 31 significant
	// bits so k * MPI[0] is exact for |k| < 2^22, which covers the small-range threshold (|x| < 2^20,
	// |k| < 2^21.4). The lower parts carry pi/8 to ~115 bits total.
	constexpr std::array<double, 3> MPI = { -0x1.921fb544p-2, -0x1.0b4611a8p-36, 0x1.d9cceba3f91f2p-68 };

	// 8/pi as a double.
	constexpr double ONE_OVER_PI = 0x1.45f306dc9c883p+1;

	// sin(y)/y on [-pi/16, pi/16] = SIN_POLY[0] + y^2 (SIN_POLY[1] + y^2 (...)). Taylor coefficients
	// rounded to double (realized error ~2^-63, well within the 4-ULP contract). sin(y) = y * poly.
	constexpr std::array<double, 6> SIN_POLY = {
		0x1.0p0,				// 1
		-0x1.5555555555555p-3,	// -1/6
		0x1.1111111111111p-7,	// 1/120
		-0x1.a01a01a01a01ap-13, // -1/5040
		0x1.71de3a556c734p-19,	// 1/362880
		-0x1.ae64567f544e4p-26, // -1/39916800
	};

	// cos(y) on [-pi/16, pi/16] = COS_POLY[0] + y^2 (COS_POLY[1] + ...). Sollya minimax, error ~2^-68.
	constexpr std::array<double, 6> COS_POLY = {
		0x1.0p0, -0x1.0p-1, 0x1.55555555554fp-5, -0x1.6c16c16b84c68p-10, 0x1.a019f88d4441ep-16, -0x1.27a8a5f9090d7p-22,
	};

	// Large-|x| reduction is handled by the shared Payne-Hanek path in sincos_payne_hanek.hpp.

} // namespace ccm::internal::sincos_double_data
