/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

// Lookup tables and constants for float sin/cos.
// Adapted from LLVM-libc (libc/src/__support/math/sincosf_float_eval.h).

#pragma once

#include <array>

namespace ccm::internal::sincos_float_data
{
	// sin(k * pi/8) for k = 0..15, generated by Sollya.
	constexpr std::array<float, 16> SIN_K_PI_OVER_8 = {
		0.0f, 0x1.87de2ap-2f,  0x1.6a09e6p-1f,	0x1.d906bcp-1f,	 1.0f,	0x1.d906bcp-1f,	 0x1.6a09e6p-1f,  0x1.87de2ap-2f,
		0.0f, -0x1.87de2ap-2f, -0x1.6a09e6p-1f, -0x1.d906bcp-1f, -1.0f, -0x1.d906bcp-1f, -0x1.6a09e6p-1f, -0x1.87de2ap-2f,
	};

	// Cody-Waite three-part -pi/8 for the small-range reduction.
	constexpr std::array<float, 3> MPI = { -0x1.921f8p-2f, -0x1.aa22p-21f, -0x1.68c234p-41f };

	// Reciprocal of pi/8. The reduction computes k = round(x * 8/pi) from it.
	constexpr float EIGHT_OVER_PI = 0x1.45f306p+1f;

	// Large-|x| reduction is handled by the shared Payne-Hanek path in sincos_payne_hanek.hpp.

} // namespace ccm::internal::sincos_float_data
