/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#pragma once

// Payne-Hanek argument reduction for sin/cos/tan, shared by the float and double kernels. Reduces a
// large |x| to k (the pi/8 multiple, low bits) and y in [-pi/16, pi/16] such that x ~ k*pi/8 + y,
// matching the small-range reduction's output so the same SIN_K table and polynomials reconstruct
// the result. The reduction multiplies x's integer mantissa by a windowed slice of the bits of
// 8/pi (a 256-bit fixed-point accumulator of (x * 8/pi) mod 16), which stays exact however large x
// becomes. Operating in double serves both kernels: a float argument casts to double exactly and
// only needs the top bits of the result.

#include "ccmath/internal/support/fp/fp_bits.hpp"
#include "ccmath/internal/support/multiply_add.hpp"

#include <array>
#include <cstdint>

namespace ccm::internal::impl::sincos_ph
{
	// Fractional bits of 8/pi, frac(8/pi) = sum FRAC_8_OVER_PI[i] * 2^(-64 (i+1)). Generated by MPFR
	// at 4096-bit precision. 32 words (2048 bits) cover the binary64 exponent range with guard bits.
	inline constexpr std::array<std::uint64_t, 32> FRAC_8_OVER_PI = {
		0x8be60db9391054a7ULL, 0xf09d5f47d4d37703ULL, 0x6d8a5664f10e4107ULL, 0xf9458eaf7aef1586ULL, 0xdc91b8e909374b80ULL, 0x1924bba827464873ULL,
		0xf877ac72c4a69cfbULL, 0xa208d7d4baed1213ULL, 0xa671c09ad17df904ULL, 0xe64758e60d4ce7d2ULL, 0x72117e2ef7e4a0ecULL, 0x7fe25fff7816603fULL,
		0xbcbc462d6829b47dULL, 0xb4d9fb3c9f2c26ddULL, 0x3d18fd9a797fa8b5ULL, 0xd49eeb1faf97c5ecULL, 0xf41ce7de294a4ba9ULL, 0xafed7ec47e357421ULL,
		0x580cc11bf1edaeafULL, 0xc33ef0826bd0d876ULL, 0xa78e45857b986c21ULL, 0x9666157c5281a102ULL, 0x37ff620135cc9cc4ULL, 0x1818555b29cea325ULL,
		0x8389ef0231ad1f10ULL, 0x670d9f3773a024aaULL, 0x0d6711da2e58729bULL, 0x76bd13455c6414faULL, 0x97fc1c14fdf8cfa0ULL, 0xcb0b793e60c9f6efULL,
		0x0cf49bbdac797be2ULL, 0x7ce87cd72bc9fc76ULL,
	};

	inline constexpr double PI_OVER_8_HI = 0x1.921fb54442d18p-2;
	inline constexpr double PI_OVER_8_LO = 0x1.1a62633145c07p-56;

	struct U128
	{
		std::uint64_t hi;
		std::uint64_t lo;
	};

	// 64 x 64 -> 128 unsigned multiply, portable and constexpr (no __int128).
	constexpr U128 mul64(std::uint64_t a, std::uint64_t b) noexcept
	{
		const std::uint64_t a_lo = a & 0xffffffffULL;
		const std::uint64_t a_hi = a >> 32;
		const std::uint64_t b_lo = b & 0xffffffffULL;
		const std::uint64_t b_hi = b >> 32;
		const std::uint64_t ll	 = a_lo * b_lo;
		const std::uint64_t lh	 = a_lo * b_hi;
		const std::uint64_t hl	 = a_hi * b_lo;
		const std::uint64_t hh	 = a_hi * b_hi;
		const std::uint64_t mid	 = (ll >> 32) + (lh & 0xffffffffULL) + (hl & 0xffffffffULL);
		const std::uint64_t lo	 = (ll & 0xffffffffULL) | (mid << 32);
		const std::uint64_t hi	 = hh + (lh >> 32) + (hl >> 32) + (mid >> 32);
		return U128{ hi, lo };
	}

	// Add a 64-bit word into the 256-bit accumulator (acc[0] low .. acc[3] high) at limb word,
	// propagating carries. The accumulator wraps mod 2^256, which is exactly the mod-16 we want.
	constexpr void add_at_word(std::uint64_t acc[4], std::uint64_t val, int word) noexcept
	{
		while (val != 0 && word < 4)
		{
			const std::uint64_t old				= acc[static_cast<std::size_t>(word)];
			acc[static_cast<std::size_t>(word)] = old + val;
			val									= (acc[static_cast<std::size_t>(word)] < old) ? 1ULL : 0ULL;
			++word;
		}
	}

	// Add (w << bitpos) into the 256-bit accumulator, bitpos may be negative (low bits are dropped,
	// they fall below the accumulator's 2^-252 resolution).
	constexpr void add_word_at(std::uint64_t acc[4], std::uint64_t w, long bitpos) noexcept
	{
		if (w == 0) { return; }
		if (bitpos < 0)
		{
			const long s = -bitpos;
			if (s >= 64) { return; }
			w >>= static_cast<unsigned>(s);
			bitpos = 0;
			if (w == 0) { return; }
		}
		if (bitpos >= 256) { return; }
		const int word			 = static_cast<int>(bitpos >> 6);
		const int off			 = static_cast<int>(bitpos & 63);
		const std::uint64_t low	 = w << off;
		const std::uint64_t high = (off != 0) ? (w >> (64 - off)) : 0ULL;
		add_at_word(acc, low, word);
		if (high != 0 && word + 1 < 4) { add_at_word(acc, high, word + 1); }
	}

	// Returns k (low bits of the pi/8 multiple) and sets y to the reduced argument in [-pi/16, pi/16].
	constexpr unsigned payne_hanek_reduce(double x, double & y) noexcept
	{
		using FPBits = support::fp::FPBits<double>;

		FPBits xbits(x);
		const bool neg				 = xbits.sign().is_neg();
		const std::uint64_t abs		 = xbits.abs().uintval();
		const int e					 = static_cast<int>((abs >> 52) & 0x7ffULL) - 1023;
		const std::uint64_t mantissa = (abs & 0xfffffffffffffULL) | 0x10000000000000ULL; // 53-bit
		const long binary_exp		 = static_cast<long>(e) - 52;						 // x = mantissa * 2^binary_exp

		// acc holds (x * 8/pi) mod 16 scaled by 2^252: top 4 bits (255..252) are the integer mod 16,
		// the rest is the fraction. 8/pi = 2 + frac(8/pi). The integer part 2 contributes 2*x.
		std::uint64_t acc[4] = { 0ULL, 0ULL, 0ULL, 0ULL };
		add_word_at(acc, mantissa, binary_exp + 1 + 252);
		for (int i = 0; i < 32; ++i)
		{
			const long shift = binary_exp - 64L * (i + 1) + 252;
			if (shift <= -128 || shift >= 256) { continue; }
			const U128 p = mul64(mantissa, FRAC_8_OVER_PI[static_cast<std::size_t>(i)]);
			add_word_at(acc, p.lo, shift);
			add_word_at(acc, p.hi, shift + 64);
		}

		unsigned k			   = static_cast<unsigned>(acc[3] >> 60) & 15U;
		const std::uint64_t a3 = acc[3] & 0x0fffffffffffffffULL; // fraction bits below the integer
		const bool round_up	   = ((a3 >> 59) & 1ULL) != 0ULL;	 // fraction >= 1/2

		// Fraction as a double-double: top 64 bits in w0 (2^-1..2^-64), next 64 in w1.
		const std::uint64_t w0 = (a3 << 4) | (acc[2] >> 60);
		const std::uint64_t w1 = (acc[2] << 4) | (acc[1] >> 60);
		double r_hi			   = static_cast<double>(w0 >> 11) * 0x1.0p-53;
		const double r_lo	   = static_cast<double>(w0 & 0x7ffULL) * 0x1.0p-64 + static_cast<double>(w1) * 0x1.0p-128;

		if (round_up)
		{
			r_hi -= 1.0; // fraction in [1/2, 1) maps to r in [-1/2, 0)
			k = (k + 1) & 15U;
		}

		// y = (r_hi + r_lo) * pi/8 with pi/8 as a double-double, rounded once into y.
		const double y_val = support::multiply_add(r_hi, PI_OVER_8_HI, support::multiply_add(r_hi, PI_OVER_8_LO, r_lo * PI_OVER_8_HI));
		y				   = neg ? -y_val : y_val;

		const unsigned k_signed = neg ? (0U - k) : k;
		return k_signed & 15U;
	}

} // namespace ccm::internal::impl::sincos_ph
