# Apply pow validation compile options to test and oracle targets.

function(ccmath_get_pow_validation_configuration_name OUT_VAR)
    set(_parts "")
    if (CCMATH_TEST_DISABLE_RUNTIME_BUILTIN)
        list(APPEND _parts "no-builtin")
    endif ()
    if (CCMATH_TEST_DISABLE_FMA)
        list(APPEND _parts "no-fma")
    elseif (CCMATH_TEST_FORCE_FMA)
        list(APPEND _parts "force-fma")
    endif ()
    if (CCMATH_DISABLE_RUNTIME_SIMD)
        list(APPEND _parts "no-simd")
    endif ()
    if (CCMATH_DISABLE_REDUCED_PRECISION_POWL)
        list(APPEND _parts "powl-strict")
    else ()
        list(APPEND _parts "powl-fallback")
    endif ()
    if (NOT _parts)
        set(_parts "default")
    endif ()
    string(REPLACE ";" "-" _name "${_parts}")
    set(${OUT_VAR} "${_name}" PARENT_SCOPE)
endfunction()

function(ccmath_apply_pow_validation_options TARGET)
    if (NOT TARGET ${TARGET})
        message(FATAL_ERROR "ccmath_apply_pow_validation_options: target ${TARGET} does not exist")
    endif ()

    if (CCMATH_TEST_DISABLE_RUNTIME_BUILTIN)
        target_compile_definitions(${TARGET} PRIVATE CCM_CONFIG_TEST_DISABLE_RUNTIME_BUILTIN_POW)
    endif ()

    if (CCMATH_TEST_DISABLE_FMA)
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang|IntelLLVM")
            if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|i[3-6]86)$")
                target_compile_options(${TARGET} PRIVATE -fno-fma)
            endif ()
        endif ()
    endif ()

    if (CCMATH_TEST_FORCE_FMA)
        if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|i[3-6]86)$")
            if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang|IntelLLVM")
                target_compile_options(${TARGET} PRIVATE -mfma)
            endif ()
        endif ()
    endif ()

    ccmath_get_pow_validation_configuration_name(_config_name)
    target_compile_definitions(${TARGET} PRIVATE CCM_CONFIG_TEST_POW_VALIDATION_NAME="${_config_name}")
endfunction()
