/*
 * Copyright (c) Ian Pike
 * Copyright (c) CCMath contributors
 *
 * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.
 * See LICENSE for more information.
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

// Portions of this code were borrowed from the LLVM Project,
// under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#pragma once

namespace ccm::internal::impl::data
{
	// Polynomial approximating tgamma(d + 2.875) on [-0.5, 0.5] generated by
	// Sollya with: P = fpminimax(tgamma(x + 2.875), [|0,1,2,3,4,5,6,7|], [|D...|], [-0.5, 0.5])

	inline constexpr double k_gamma_coeffs[8] = {
		0x1.c9a76b7de6f60p+0, 0x1.8f2754874fe83p+0, 0x1.0d11cba0c229fp+0, 0x1.e1f47c012064dp-2,
		0x1.828b9f2afb74fp-3, 0x1.e1cc49d830795p-5, 0x1.2c9af3e686836p-6, 0x1.1bf60c7e311f6p-8};

	inline constexpr double k_gamma_base = 0x1.7p+1;

	inline constexpr double k_tiny_a = 0x1.fa658c23b1578p-1;
	inline constexpr double k_tiny_b = 0x1.d0a118f324b63p-1;
	inline constexpr double k_tiny_c = 0x1.2788cfc6fb619p-1;

} // namespace ccm::internal::impl::data
