#!/usr/bin/env python3
"""Emit powl_ld80_tables.hpp from pow Sollya tables and ld80-native splits."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/powl_ld80_tables.hpp"
POW_IMPL = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/pow_impl.hpp"
POWF_DATA = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/powf_data.hpp"
COMMON = ROOT / "include/ccmath/internal/support/common_math_constants.hpp"


def extract_braced_array(text: str, name: str) -> list[str]:
    start = text.find(f"{name} = {{")
    if start < 0:
        raise RuntimeError(f"missing array {name}")
    i = start + len(name) + 4
    depth = 1
    while i < len(text) and depth:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
        i += 1
    body = text[start + len(name) + 4 : i - 1]
    body = re.sub(r"//.*", "", body)
    tokens: list[str] = []
    depth = 0
    cur = ""
    for ch in body:
        if ch == "{":
            depth += 1
            cur += ch
        elif ch == "}":
            depth -= 1
            cur += ch
            if depth == 0:
                tokens.append(cur.strip())
                cur = ""
        elif ch == "," and depth == 0:
            if cur.strip():
                tokens.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        tokens.append(cur.strip())
    return tokens


def to_ld(token: str) -> str:
    token = token.strip()
    if token in ("0", "0.0", "0.0L"):
        return "0.0L"
    if token.endswith("L"):
        return token
    return f"{token}L"


def parse_triple_fields(token: str) -> tuple[str, str, str]:
    inner = token[token.find("{") :].strip("{}")
    parts = [p.strip() for p in inner.split(",")]
    if len(parts) != 3:
        raise RuntimeError(f"expected TripleDouble, got {token}")
    return parts[0], parts[1], parts[2]


def cpp_array(name: str, rows: list[str]) -> list[str]:
    return [f"\tinline constexpr std::array<long double, {len(rows)}> {name} = {{", *rows, "\t};", ""]


def main() -> int:
    pow_impl = POW_IMPL.read_text(encoding="utf-8")
    powf_data = POWF_DATA.read_text(encoding="utf-8")
    common = COMMON.read_text(encoding="utf-8")

    # POW_LOG2_COEFFS / POW_EXP2_COEFFS are NOT the binary64 pow coefficients. Those are degree
    # limited to ~2^-56 (log2) / ~2^-60 (exp2) relative error, which is below a double ULP but
    # several long double ULP. These are refit by Sollya at double-extended precision for the
    # 64-bit x87 significand:
    #   LOG2: fpminimax(log2(1+x)/x, 7, [|DE...|], [-2^-8, 2^-7])      supnorm ~2^-66
    #   EXP2: fpminimax(2^(x/64),    6, [|1,DE...|], [-1/2, 1/2])      supnorm ~2^-71
    # See tools/proofs/math/power/validate_powl_ld80_kernel.sollya.
    log2 = [
        "0x1.71547652b82fe178p0",
        "-0x1.71547652b82fe144p-1",
        "0x1.ec709dc3a03558dep-2",
        "-0x1.71547652b7385bf8p-2",
        "0x1.2776c51d878b842ep-2",
        "-0x1.ec70a8a71c0b750ap-3",
        "0x1.a60c087e7df298fap-3",
        "-0x1.6987a26ef5e05516p-3",
    ]
    exp2 = [
        "0x1p0",
        "0x1.62e42fefa39ef366p-7",
        "0x1.ebfbdff82c58ea5ep-15",
        "0x1.c6b08d704846aad6p-23",
        "0x1.3b2ab6fba696a65ap-31",
        "0x1.5d881a9521b2c8b8p-40",
        "0x1.43090c2f8c21d398p-49",
    ]
    rd = extract_braced_array(common, "RD")
    cd = extract_braced_array(common, "CD")
    log2_td = extract_braced_array(powf_data, "LOG2_R_TD")
    exp_mid = extract_braced_array(common, "EXP2_MID1")

    exp2_hi = [f"\t\t{to_ld(parse_triple_fields(t)[2])}," for t in exp_mid]
    exp2_mid = [f"\t\t{to_ld(parse_triple_fields(t)[1])}," for t in exp_mid]
    log2_hi = [f"\t\t{to_ld(parse_triple_fields(t)[2])}," for t in log2_td]
    log2_mid = [f"\t\t{to_ld(parse_triple_fields(t)[1])}," for t in log2_td]
    log2_lo = [f"\t\t{to_ld(parse_triple_fields(t)[0])}," for t in log2_td]

    lines = [
        "/*",
        " * Copyright (c) Ian Pike",
        " * Copyright (c) CCMath contributors",
        " *",
        " * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.",
        " * See LICENSE for more information.",
        " *",
        " * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception",
        " */",
        "",
        "// Generated by tools/proofs/math/power/generate_powl_ld80_tables.py",
        "// POW_LOG2_COEFFS / POW_EXP2_COEFFS are Sollya minimax polynomials refit at double-extended",
        "// precision for the 64-bit x87 significand (LOG2 degree 7, supnorm ~2^-66; EXP2 degree 6,",
        "// supnorm ~2^-71). The binary64 pow coefficients are degree-limited to ~2^-56/2^-60 and cannot",
        "// reach long double precision. Reduction/exp tables (RD/CD/LOG2_R/EXP2) reuse the binary64",
        "// hi/mid/lo splits (EXP2_MID1, LOG2_R_TD), which already carry well over 64 bits as long double.",
        "",
        "#pragma once",
        "",
        "#if defined(CCM_TYPES_LONG_DOUBLE_IS_FLOAT80)",
        "",
        "#include <array>",
        "",
        "namespace ccm::gen::impl::internal::impl::powl_ld80_tables",
        "{",
        "",
        "\tinline constexpr std::array<long double, 8> POW_LOG2_COEFFS = {",
    ]
    lines.extend(f"\t\t{to_ld(t)}," for t in log2)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 7> POW_EXP2_COEFFS = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in exp2)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 128> RD = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in rd)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 128> CD = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in cd)
    lines.extend(["\t};", ""])
    lines.extend(cpp_array("EXP2_HI", exp2_hi))
    lines.extend(cpp_array("EXP2_MID", exp2_mid))
    lines.extend(cpp_array("LOG2_R_HI", log2_hi))
    lines.extend(cpp_array("LOG2_R_MID", log2_mid))
    lines.extend(cpp_array("LOG2_R_LO", log2_lo))
    lines.extend(["} // namespace ccm::gen::impl::internal::impl::powl_ld80_tables", "", "#endif", ""])

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
