#!/usr/bin/env python3
"""Emit powl_ld80_tables.hpp from existing pow Sollya-derived constants."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/powl_ld80_tables.hpp"
POW_IMPL = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/pow_impl.hpp"
POWF_DATA = ROOT / "include/ccmath/internal/math/generic/func/power/pow_impl/powf_data.hpp"
COMMON = ROOT / "include/ccmath/internal/support/common_math_constants.hpp"


def extract_braced_array(text: str, name: str) -> list[str]:
    start = text.find(f"{name} = {{")
    if start < 0:
        raise RuntimeError(f"missing array {name}")
    i = start + len(name) + 4
    depth = 1
    while i < len(text) and depth:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
        i += 1
    body = text[start + len(name) + 4 : i - 1]
    body = re.sub(r"//.*", "", body)
    tokens: list[str] = []
    depth = 0
    cur = ""
    for ch in body:
        if ch == "{":
            depth += 1
            cur += ch
        elif ch == "}":
            depth -= 1
            cur += ch
            if depth == 0:
                tokens.append(cur.strip())
                cur = ""
        elif ch == "," and depth == 0:
            if cur.strip():
                tokens.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        tokens.append(cur.strip())
    return tokens


def to_ld(token: str) -> str:
    token = token.strip()
    if token in ("0", "0.0", "0.0L"):
        return "0.0L"
    if token.endswith("L"):
        return token
    return f"{token}L"


def parse_triple(token: str) -> str:
    inner = token[token.find("{") :].strip("{}")
    parts = [p.strip() for p in inner.split(",")]
    return f"ccm::types::TripleDouble{{ {parts[0]}L, {parts[1]}L, {parts[2]}L }}"


def main() -> int:
    pow_impl = POW_IMPL.read_text(encoding="utf-8")
    powf_data = POWF_DATA.read_text(encoding="utf-8")
    common = COMMON.read_text(encoding="utf-8")

    log2 = extract_braced_array(pow_impl, "POW_LOG2_COEFFS")
    exp2 = extract_braced_array(pow_impl, "POW_EXP2_COEFFS")
    rd = extract_braced_array(common, "RD")
    cd = extract_braced_array(common, "CD")
    log2_td = extract_braced_array(powf_data, "LOG2_R_TD")
    exp_mid = extract_braced_array(common, "EXP2_MID1")

    lines = [
        "/*",
        " * Copyright (c) Ian Pike",
        " * Copyright (c) CCMath contributors",
        " *",
        " * CCMath is provided under the Apache-2.0 License WITH LLVM-exception.",
        " * See LICENSE for more information.",
        " *",
        " * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception",
        " */",
        "",
        "// Generated by tools/proofs/math/power/generate_powl_ld80_tables.py",
        "// from existing binary64 pow Sollya tables (same intervals and split recipes).",
        "",
        "#pragma once",
        "",
        "#if defined(CCM_TYPES_LONG_DOUBLE_IS_FLOAT80)",
        "",
        '#include "ccmath/internal/types/triple_double.hpp"',
        "",
        "#include <array>",
        "",
        "namespace ccm::gen::impl::internal::impl::powl_ld80_tables",
        "{",
        "",
        "\tinline constexpr std::array<long double, 7> POW_LOG2_COEFFS = {",
    ]
    lines.extend(f"\t\t{to_ld(t)}," for t in log2)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 6> POW_EXP2_COEFFS = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in exp2)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 128> RD = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in rd)
    lines.extend(["\t};", "", "\tinline constexpr std::array<long double, 128> CD = {"])
    lines.extend(f"\t\t{to_ld(t)}," for t in cd)
    lines.extend(["\t};", "", "\tinline constexpr std::array<ccm::types::TripleDouble, 128> LOG2_R_TD = {"])
    lines.extend(f"\t\t{parse_triple(t)}," for t in log2_td)
    lines.extend(["\t};", "", "\tinline constexpr std::array<ccm::types::TripleDouble, 64> EXP2_MID1 = {"])
    lines.extend(f"\t\t{parse_triple(t)}," for t in exp_mid)
    lines.extend(["\t};", "", "} // namespace ccm::gen::impl::internal::impl::powl_ld80_tables", "", "#endif", ""])

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
