#!/usr/bin/env python3
"""Generate Meson and Premake secondary build files from ccmath-build-manifest.json."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


GENERATED_BEGIN_MESON = "# BEGIN GENERATED LIBRARY MANIFEST"
GENERATED_END_MESON = "# END GENERATED LIBRARY MANIFEST"
GENERATED_BEGIN_PREMAKE = "-- BEGIN GENERATED LIBRARY MANIFEST"
GENERATED_END_PREMAKE = "-- END GENERATED LIBRARY MANIFEST"


def load_manifest(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def meson_define_args(options: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    for option in options:
        meson_name = option["meson_option"]
        define = option["define"]
        lines.append(
            f"if get_option('{meson_name}')\n"
            f"  _ccmath_defines += '-D{define}'\n"
            f"endif"
        )
    return "\n".join(lines)


def meson_options_txt(options: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.",
        "# CMake is the primary build system.",
        "",
    ]
    for option in options:
        default = "true" if option["meson_default"] else "false"
        description = option["description"].replace("'", "\\'")
        lines.append(
            f"option('{option['meson_option']}', type: 'boolean', value: {default}, "
            f"description: '{description}')"
        )
    lines.append("")
    return "\n".join(lines)


def meson_build_content(manifest: dict[str, Any], source_dir: Path, standalone: bool) -> str:
    options = manifest["options"]
    version = manifest["version"]
    cpp_standard = manifest["cpp_standard"]
    include_dirs = manifest["include_dirs"]
    build_include = next(
        (entry for entry in include_dirs if "include" in entry and entry != "include"),
        "include",
    )

    project_line = (
        f"project('{manifest['name']}', 'cpp',\n"
        f"  version: '{version}',\n"
        f"  meson_version: '>=1.0.0',\n"
        f"  default_options: ['cpp_std=c++{cpp_standard}'],\n"
        f")"
    )

    if standalone:
        source_root = Path(manifest["source_dir"])
        build_include = Path(manifest["build_dir"]) / "include"
        header = [
            "# Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.",
            "# CMake is the primary build system.",
            "#",
            "# Requires a prior CMake configure so version.hpp exists under the build include dir.",
            "#",
            "# Usage:",
            "#   meson setup build-meson <path-to-this-directory>",
            "#   meson compile -C build-meson",
            "",
            project_line,
            "",
            "_ccmath_defines = []",
            meson_define_args(options),
            "",
            "ccmath_inc = include_directories(",
            f"  '{source_root / 'include'}',",
            f"  '{build_include}',",
            ")",
            "",
            "ccmath_dep = declare_dependency(",
            "  include_directories: ccmath_inc,",
            "  compile_args: _ccmath_defines,",
            ")",
            "",
            "executable(",
            "  'ccmath-smoke',",
            f"  '{source_root / 'examples/smoke/constexpr_smoke.cpp'}',",
            "  dependencies: ccmath_dep,",
            ")",
            "",
        ]
        return "\n".join(header)

    header = [
        "# Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.",
        "",
        project_line,
        "",
        "version_conf = configuration_data()",
        f"version_conf.set('CCMATH_VERSION_MAJOR', {version.split('.')[0]})",
        f"version_conf.set('CCMATH_VERSION_MINOR', {version.split('.')[1]})",
        f"version_conf.set('CCMATH_VERSION_PATCH', {version.split('.')[2]})",
        "configure_file(",
        f"  input: '{source_dir / manifest['version_template']}',",
        "  output: 'ccmath/version.hpp',",
        "  configuration: version_conf,",
        "  format: 'cmake',",
        "  install: false,",
        ")",
        "",
        "_ccmath_defines = []",
        meson_define_args(options),
        "",
        "ccmath_inc = include_directories(",
        f"  '{source_dir / 'include'}',",
        f"  '{Path(build_include).as_posix() if Path(build_include).is_absolute() else source_dir / build_include}',",
        ")",
        "",
        "ccmath_dep = declare_dependency(",
        "  include_directories: ccmath_inc,",
        "  compile_args: _ccmath_defines,",
        ")",
        "",
        "executable(",
        "  'ccmath-smoke',",
        f"  '{source_dir / 'examples/smoke/constexpr_smoke.cpp'}',",
        "  dependencies: ccmath_dep,",
        ")",
        "",
    ]
    return "\n".join(header)


def premake_trigger_name(meson_option: str) -> str:
    return "ccmath-" + meson_option.replace("_", "-")


def premake_options(options: list[dict[str, Any]], indent: str = "") -> str:
    lines: list[str] = []
    for option in options:
        default = "true" if option["meson_default"] else "false"
        description = option["description"].replace('"', '\\"')
        trigger = premake_trigger_name(option["meson_option"])
        lines.extend(
            [
                f"{indent}newoption {{",
                f'{indent}    trigger = "{trigger}",',
                f'{indent}    description = "{description}",',
                f'{indent}    allowed = {{ {{ "true", "Enable" }}, {{ "false", "Disable" }} }},',
                f'{indent}    default = "{default}",',
                f"{indent}}}",
                "",
            ]
        )
    return "\n".join(lines)


def premake_project_body(
    manifest: dict[str, Any],
    source_dir: Path,
    *,
    premake_location: Path,
    option_indent: str = "",
    body_indent: str = "",
    relative_paths: bool = False,
) -> str:
    options = manifest["options"]
    build_include = Path(manifest["build_dir"]) / "include"
    if relative_paths:
        include_dir = "include"
        build_include_dir = os.path.relpath(build_include, source_dir.resolve()).replace("\\", "/")
        smoke_source = "examples/smoke/constexpr_smoke.cpp"
        location_dir = os.path.relpath(premake_location, source_dir.resolve()).replace("\\", "/")
    else:
        include_dir = f"{source_dir.as_posix()}/include"
        build_include_dir = build_include.as_posix()
        smoke_source = f"{source_dir.as_posix()}/examples/smoke/constexpr_smoke.cpp"
        location_dir = premake_location.as_posix()

    return "\n".join(
        [
            premake_options(options, indent=option_indent),
            "",
            f'{body_indent}project "ccmath-smoke"',
            f'{body_indent}    kind "ConsoleApp"',
            f'{body_indent}    language "C++"',
            f'{body_indent}    location "{location_dir}"',
            f'{body_indent}    includedirs {{ "{include_dir}", "{build_include_dir}" }}',
            f'{body_indent}    files {{ "{smoke_source}" }}',
            "",
            premake_define_blocks_with_indent(options, body_indent),
            "",
            f'{body_indent}filter "configurations:Debug"',
            f'{body_indent}    symbols "On"',
            f'{body_indent}    optimize "Off"',
            "",
            f'{body_indent}filter "configurations:Release"',
            f'{body_indent}    symbols "Off"',
            f'{body_indent}    optimize "Speed"',
            "",
            f"{body_indent}filter {{}}",
            "",
        ]
    )


def premake_define_blocks_with_indent(
    options: list[dict[str, Any]],
    indent: str,
) -> str:
    blocks: list[str] = []
    for option in options:
        trigger = premake_trigger_name(option["meson_option"])
        define = option["define"]
        blocks.append(
            f'{indent}filter {{ "options:{trigger}=true" }}\n'
            f'{indent}    defines {{ "{define}" }}\n'
            f"{indent}filter {{}}"
        )
    return "\n\n".join(blocks)


def premake_content(
    manifest: dict[str, Any],
    source_dir: Path,
    standalone: bool,
    *,
    premake_location: Path | None = None,
) -> str:
    cpp_standard = manifest["cpp_standard"]
    resolved_location = premake_location or (Path(manifest["build_dir"]) / "premake-smoke")
    header = [
        "-- Generated by tools/gen_secondary_builds.py from ccmath-build-manifest.json.",
        "-- CMake is the primary build system.",
        "",
    ]

    if standalone:
        workspace_location = "." if premake_location is not None else source_dir.as_posix()
        header.extend(
            [
                f'workspace "{manifest["name"]}"',
                f'    location "{workspace_location}"',
                '    configurations { "Debug", "Release" }',
                '    architecture "x86_64"',
                f'    cppdialect "C++{cpp_standard}"',
                "",
            ]
        )

    fragment_indent = "" if standalone else "    "
    header.append(
        premake_project_body(
            manifest,
            source_dir,
            premake_location=resolved_location,
            option_indent=fragment_indent,
            body_indent=fragment_indent,
            relative_paths=premake_location is not None,
        )
    )
    return "\n".join(header)


def root_meson_wrapper(manifest: dict[str, Any]) -> str:
    generated = "\n".join(
        [
            f"project('{manifest['name']}', 'cpp',",
            f"  version: '{manifest['version']}',",
            f"  meson_version: '>=1.0.0',",
            f"  default_options: ['cpp_std=c++{manifest['cpp_standard']}'],",
            ")",
            "",
            "# Regenerate this block:",
            "#   cmake --build <build-dir> --target ccmath-generate-secondary-builds",
            "",
            "subdir('cmake/gen')",
            "",
        ]
    )

    return "\n".join(
        [
            "# CCMath secondary build (library consumption). CMake is the primary build system.",
            "# Regenerate generated files:",
            "#   cmake --build <build-dir> --target ccmath-generate-secondary-builds",
            "",
            GENERATED_BEGIN_MESON,
            generated.rstrip(),
            GENERATED_END_MESON,
            "",
        ]
    )


def root_premake_wrapper(manifest: dict[str, Any], source_dir: Path) -> str:
    header = [
        "-- CCMath secondary build (library consumption). CMake is the primary build system.",
        "-- Regenerate generated files:",
        "--   cmake --build <build-dir> --target ccmath-generate-secondary-builds",
        "",
        GENERATED_BEGIN_PREMAKE,
    ]
    body = premake_content(
        manifest,
        source_dir,
        standalone=True,
        premake_location=source_dir / "out" / "premake",
    ).splitlines()  # premake_location selects relative path mode
    # Drop duplicate generator header from the embedded standalone body.
    while body and (
        body[0].startswith("-- Generated by tools/gen_secondary_builds.py")
        or body[0].strip() == ""
        or body[0].startswith("-- CMake is the primary")
    ):
        body.pop(0)
    return "\n".join(header + body + [GENERATED_END_PREMAKE, ""])


def cmake_gen_meson(manifest: dict[str, Any], source_dir: Path) -> str:
    options = manifest["options"]

    build_include = Path(manifest["build_dir"]) / "include"
    gen_subdir = source_dir / "cmake" / "gen"
    try:
        include_rel = Path("..") / ".." / "include"
        build_include_rel = Path(
            os.path.relpath(build_include, gen_subdir.resolve())
        ).as_posix()
    except ValueError:
        build_include_rel = build_include.as_posix()

    return "\n".join(
        [
            "# Generated by tools/gen_secondary_builds.py. Do not edit by hand.",
            "# Requires a prior CMake configure so version.hpp exists under the build include dir.",
            "",
            "_ccmath_defines = []",
            meson_define_args(options),
            "",
            "ccmath_inc = include_directories(",
            f"  '{include_rel.as_posix()}',",
            f"  '{build_include_rel}',",
            ")",
            "",
            "ccmath_dep = declare_dependency(",
            "  include_directories: ccmath_inc,",
            "  compile_args: _ccmath_defines,",
            ")",
            "",
            "executable(",
            "  'ccmath-smoke',",
            "  '../../examples/smoke/constexpr_smoke.cpp',",
            "  dependencies: ccmath_dep,",
            ")",
            "",
        ]
    )


def write_outputs(
    manifest: dict[str, Any],
    output_dir: Path,
    source_dir: Path,
    update_root: bool,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    (output_dir / "meson.build").write_text(
        meson_build_content(manifest, source_dir, standalone=True),
        encoding="utf-8",
    )
    options_txt = meson_options_txt(manifest["options"])

    (output_dir / "meson_options.txt").write_text(options_txt, encoding="utf-8")
    (output_dir / "premake5.lua").write_text(
        premake_content(manifest, source_dir, standalone=True),
        encoding="utf-8",
    )

    if update_root:
        gen_dir = source_dir / "cmake" / "gen"
        gen_dir.mkdir(parents=True, exist_ok=True)
        (gen_dir / "meson.build").write_text(
            cmake_gen_meson(manifest, source_dir),
            encoding="utf-8",
        )
        (source_dir / "meson_options.txt").write_text(options_txt, encoding="utf-8")
        (source_dir / "meson.build").write_text(
            root_meson_wrapper(manifest),
            encoding="utf-8",
        )
        (source_dir / "premake5.lua").write_text(
            root_premake_wrapper(manifest, source_dir),
            encoding="utf-8",
        )


def check_root_markers(source_dir: Path) -> int:
    for name in ("meson.build", "premake5.lua"):
        path = source_dir / name
        if not path.exists():
            print(f"check failed: missing {path}", file=sys.stderr)
            return 1
        text = path.read_text(encoding="utf-8")
        markers = (
            (GENERATED_BEGIN_MESON, GENERATED_END_MESON)
            if name == "meson.build"
            else (GENERATED_BEGIN_PREMAKE, GENERATED_END_PREMAKE)
        )
        if markers[0] not in text or markers[1] not in text:
            print(f"check failed: markers missing in {path}", file=sys.stderr)
            return 1
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--update-root", action="store_true")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = load_manifest(args.manifest)

    if args.check:
        return check_root_markers(args.source_dir)

    write_outputs(
        manifest=manifest,
        output_dir=args.output_dir,
        source_dir=args.source_dir.resolve(),
        update_root=args.update_root,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
