name: ci-linux

on:
  push:
    tags-ignore:
      - v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # GCC Debug
          - name: gcc-debug
            configurePreset: ninja-gcc-debug
            buildPreset: build-ninja-gcc-debug
            testPreset: test-ninja-gcc-debug
            cxx_version: 17

          - name: gcc-debug-cxx20
            configurePreset: ninja-gcc-debug
            buildPreset: build-ninja-gcc-debug
            testPreset: test-ninja-gcc-debug
            cxx_version: 20

          # GCC Release
          - name: gcc-release
            configurePreset: ninja-gcc-release
            buildPreset: build-ninja-gcc-release
            testPreset: test-ninja-gcc-release
            cxx_version: 17

          - name: gcc-release-cxx20
            configurePreset: ninja-gcc-release
            buildPreset: build-ninja-gcc-release
            testPreset: test-ninja-gcc-release
            cxx_version: 20

          # Clang Debug
          - name: clang-debug
            configurePreset: ninja-clang-debug
            buildPreset: build-ninja-clang-debug
            testPreset: test-ninja-clang-debug
            cxx_version: 17

          - name: clang-debug-cxx20
            configurePreset: ninja-clang-debug
            buildPreset: build-ninja-clang-debug
            testPreset: test-ninja-clang-debug
            cxx_version: 20

          # Clang Release
          - name: clang-release
            configurePreset: ninja-clang-release
            buildPreset: build-ninja-clang-release
            testPreset: test-ninja-clang-release
            cxx_version: 17

          - name: clang-release-cxx20
            configurePreset: ninja-clang-release
            buildPreset: build-ninja-clang-release
            testPreset: test-ninja-clang-release
            cxx_version: 20

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            ./**/CMakeFiles
            ./**/CMakeCache.txt
            ./**/out
          key: ${{ runner.os }}-${{ matrix.name }}

      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -yqq --no-install-recommends ninja-build

      - name: Configure
        run: cmake --preset="${{ matrix.configurePreset }}" -DCCMATH_ENABLE_AGGRESSIVE_WARNINGS=ON -DCCMATH_ENABLE_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: cmake --build --preset="${{ matrix.buildPreset }}"

      - name: Test
        run: ctest --preset="${{ matrix.testPreset }}" --output-on-failure --schedule-random -F
