name: ci-macos
on:
  push:
    tags-ignore:
      - v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  setup:
    runs-on: macos-14
    outputs:
      cache-hit: ${{ steps.cache-build.outputs.cache-hit }}
    steps:
      - name: Cache Build Files
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-cmake-build

  build-and-test:
    runs-on: macos-14
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        compiler: [ ninja-clang, ninja-gcc ]
        cxx_version: [ 17, 20 ]
        target: [ Debug, Release ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Install Ninja
        run: brew install ninja

      - name: Configure CMake
        run: |
          cmake -S . --preset=${{ matrix.compiler }} -B build -DCMAKE_CXX_STANDARD=${{ matrix.cxx_version }}

      - name: Build
        run: cmake --build build --config=${{ matrix.target }}

      - name: Test
        run: cd build && ctest -C ${{ matrix.target }} --output-on-failure
