name: ci-macos
on:
  push:
    tags-ignore:
      - v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        compiler: [ninja-clang, ninja-gcc]
        cxx_version: [17, 20]
        target: [Debug, Release]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache CMake build files
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ matrix.compiler }}-${{ matrix.cxx_version }}-${{ matrix.target }}
          restore-keys: |
            ${{ runner.os }}-cmake-${{ matrix.compiler }}-${{ matrix.cxx_version }}-
            ${{ runner.os }}-cmake-${{ matrix.compiler }}-

      - name: install homebrew formulae
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: install ninja
        run: brew install ninja

      - name: update AppleClang to 14.0.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer

      - name: configure
        run: cmake -S . --preset=${{matrix.compiler}} -B build -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}}

      - name: build
        run: cmake --build build --config=${{matrix.target}}

  test:
    runs-on: macos-14
    needs: build
    strategy:
      fail-fast: false
      matrix:
        compiler: [ninja-clang, ninja-gcc]
        cxx_version: [17, 20]
        target: [Debug, Release]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache CMake build files
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ matrix.compiler }}-${{ matrix.cxx_version }}-${{ matrix.target }}

      - name: test
        run: cd build && ctest -C ${{matrix.target}} --output-on-failure
