name: ci-windows

on:
  push:
    tags-ignore:
      - v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: vs22-debug-cxx17
            configurePreset: vs22-debug
            buildPreset: build-vs22-debug
            testPreset: test-vs22-debug
            cxx_version: 17

          - name: vs22-debug-cxx20
            configurePreset: vs22-debug
            buildPreset: build-vs22-debug
            testPreset: test-vs22-debug
            cxx_version: 20

          - name: vs22-release-cxx17
            configurePreset: vs22-release
            buildPreset: build-vs22-release
            testPreset: test-vs22-release
            cxx_version: 17

          - name: vs22-release-cxx20
            configurePreset: vs22-release
            buildPreset: build-vs22-release
            testPreset: test-vs22-release
            cxx_version: 20

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            ./**/CMakeFiles
            ./**/CMakeCache.txt
            ./**/out
          key: ${{ runner.os }}-${{ matrix.name }}

      - name: Configure
        run: cmake --preset="${{ matrix.configurePreset }}" -DCMAKE_CXX_STANDARD="${{ matrix.cxx_version }}"

      - name: Build
        run: cmake --build --preset="${{ matrix.buildPreset }}"

      - name: Test
        run: ctest --preset="${{ matrix.testPreset }}" --output-on-failure --schedule-random -F
