name: fuzz

on:
  push:
    tags-ignore:
      - v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  libfuzzer-smoke:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        run: brew install ninja llvm lld

      - name: Configure fuzz targets
        run: |
          LLVM_PREFIX="$(brew --prefix llvm)"
          cmake --preset=ninja-fuzz-debug \
            -DCMAKE_C_COMPILER="${LLVM_PREFIX}/bin/clang" \
            -DCMAKE_CXX_COMPILER="${LLVM_PREFIX}/bin/clang++" \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"

      - name: Build fuzz targets
        run: cmake --build --preset=build-ninja-fuzz-debug

      - name: Fuzz smoke tests
        run: ctest --preset=test-ninja-fuzz-debug -C Debug --output-on-failure
