name: lint

on:
  pull_request:
    paths:
      - '**.hpp'

permissions:
  contents: read

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Install clang-format
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
        with:
          clangformat: 20.1.8

      - name: Check clang-format
        run: bash tools/ensure_format.sh
