name: lint

on:
  pull_request:
    paths:
      - '**.hpp'

permissions:
  contents: read

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install clang-format
        uses: aminya/setup-cpp@004edc19527a83d56cda032658aab55c5e2ed48f # v1.7.0
        with:
          clangformat: 17.0.5

      - name: Run clang-format
        run: |
          find include -name '*.hpp' |  xargs clang-format -i -style=file -fallback-style=none
          git diff --exit-code
