/*
 * Copyright (c) 2024-Present Ian Pike
 * Copyright (c) 2024-Present ccmath contributors
 *
 * This library is provided under the MIT License.
 * See LICENSE for more information.
 */

#pragma once

#ifdef CCM_DISABLE_GCC_WARNING
    #undef CCM_DISABLE_GCC_WARNING
#endif

#ifdef CCM_RESTORE_GCC_WARNING
    #undef CCM_RESTORE_GCC_WARNING
#endif

#ifdef CCM_ENABLE_GCC_WARNING_AS_ERROR
    #undef CCM_ENABLE_GCC_WARNING_AS_ERROR
#endif

#ifdef CCM_DISABLE_GCC_WARNING_AS_ERROR
    #undef CCM_DISABLE_GCC_WARNING_AS_ERROR
#endif

#ifdef CCM_ENABLE_IGNORE_GCC_WARNING
    #undef CCM_ENABLE_IGNORE_GCC_WARNING
#endif

#ifdef CCM_DISABLE_IGNORE_GCC_WARNING
    #undef CCM_DISABLE_IGNORE_GCC_WARNING
#endif

#ifdef CCM_DISABLE_CLANG_WARNING
    #undef CCM_DISABLE_CLANG_WARNING
#endif

#ifdef CCM_RESTORE_CLANG_WARNING
    #undef CCM_RESTORE_CLANG_WARNING
#endif

#ifdef CCM_ENABLE_CLANG_WARNING_AS_ERROR
    #undef CCM_ENABLE_CLANG_WARNING_AS_ERROR
#endif

#ifdef CCM_DISABLE_CLANG_WARNING_AS_ERROR
    #undef CCM_DISABLE_CLANG_WARNING_AS_ERROR
#endif

#ifdef CCM_DISABLE_MSVC_WARNING
    #undef CCM_DISABLE_MSVC_WARNING
#endif

#ifdef CCM_RESTORE_MSVC_WARNING
    #undef CCM_RESTORE_MSVC_WARNING
#endif

#ifdef CCM_ENABLE_MSVC_WARNING_AS_ERROR
    #undef CCM_ENABLE_MSVC_WARNING_AS_ERROR
#endif

#ifdef CCM_DISABLE_MSVC_WARNING_AS_ERROR
    #undef CCM_DISABLE_MSVC_WARNING_AS_ERROR
#endif

#ifdef CCM_DISABLE_ALL_MSVC_WARNINGS
    #undef CCM_DISABLE_ALL_MSVC_WARNINGS
#endif

#ifdef CCM_RESTORE_ALL_MSVC_WARNINGS
    #undef CCM_RESTORE_ALL_MSVC_WARNINGS
#endif
